from .base import BaseModel

class RelacionesPosteriores(BaseModel):
    """Data model for BOE auxiliary data.

    Generated from: https://www.boe.es/datosabiertos/api/datos-auxiliares/relaciones-posteriores
    """
    ADHESION = 430
    CORRECCION_DE_ERRATAS = 202
    CORRECCION_DE_ERRORES = 201
    CONFLICTO = 520
    CUESTION = 530
    RECURSO = 694
    SE_ACEPTA = 400
    SE_ACTUALIZA = 404
    SE_AMPLIA = 406
    SE_ANULA = 220
    SE_ANULAN_LAS_EDICIONES_ANTERIORES_DE_LAS_NORMAS = 221
    SE_APRUEBA = 420
    SE_AUTORIZA = 421
    SE_ANADE = 407
    SE_COMPLETA = 408
    SE_CORRIGEN_ERRATAS = 204
    SE_CORRIGEN_ERRORES = 203
    SE_DECLARA = 470
    SE_DECLARA_LA_VIGENCIA = 480
    SE_DEJA_SIN_EFECTO = 230
    SE_DEROGA = 210
    SE_DEROGA_CON_LA_EXCEPCION_INDICADA = 212
    SE_DEROGA_EN_CUANTO_SE_OPONGA = 213
    SE_DEROGA_EN_LA_FORMA_INDICADA = 214
    SE_DEROGA_LO_INDICADO = 211
    SE_DEROGA_PARCIALMENTE = 215
    SE_DEROGA_TACITAMENTE = 217
    SE_DESARROLLA = 490
    SE_DICTA = 693
    SE_DICTA_DE_CONFORMIDAD = 440
    SE_DICTA_EN_RELACION = 331
    SE_DISPONE_EL_CUMPLIMIENTO_DE_LA_SENTENCIA = 540
    SE_INTERPRETA = 402
    SE_MODIFICA = 270
    SE_MODIFICA_EL_PLAN = 271
    SE_MODIFICAN_DETERMINADOS_PRECEPTOS = 272
    SE_PRORROGA = 401
    SE_PUBLICA = 300
    SE_PUBLICA_ACUERDO_DE_CONVALIDACION = 301
    SE_PUBLICA_ENMIENDA = 247
    SE_PUBLICA_EL_TEXTO_REVISADO = 303
    SE_RATIFICA = 422
    SE_SUPRIME = 235
    SE_SUSPENDE = 231
    SE_SUSTITUYE = 245
    SE_TRANSPONE = 426
    SE_TRANSPONE_PARCIALMENTE = 427
    SE_DEROGA_DE_FORMA_REITERADA = 216
