from .base import BaseModel

class RelacionesAnteriores(BaseModel):
    """Data model for BOE auxiliary data.

    Generated from: https://www.boe.es/datosabiertos/api/datos-auxiliares/relaciones-anteriores
    """
    ACEPTA = 400
    ACTUALIZA = 404
    ADHESION = 430
    AMPLIA = 406
    ANULA = 220
    ANULA_LAS_EDICIONES_ANTERIORES_DE_LAS_NORMAS = 221
    APRUEBA = 420
    AUTORIZA = 421
    ANADE = 407
    CITA = 330
    COMPLETA = 408
    CORRECCION_DE_ERRATAS = 202
    CORRECCION_DE_ERRORES = 201
    CORRIGE_ERRATAS = 204
    CORRIGE_ERRORES = 203
    CONFLICTO_PROMOVIDO_EN_RELACION_CON = 520
    CUESTION_PROMOVIDA_POR_SUPUESTA_INCONSTITUCIONALIDAD = 530
    DE_CONFORMIDAD_CON = 440
    DECLARA = 470
    DECLARA_LA_VIGENCIA = 480
    DEJA_SIN_EFECTO = 230
    DEROGA = 210
    DEROGA_CON_LA_EXCEPCION_INDICADA = 212
    DEROGA_DE_FORMA_REITERADA = 216
    DEROGA_EN_CUANTO_SE_OPONGA = 213
    DEROGA_EN_LA_FORMA_INDICADA = 214
    DEROGA_LO_INDICADO = 211
    DEROGA_PARCIALMENTE = 215
    DEROGA_TACITAMENTE = 217
    DESARROLLA = 490
    DICTADA = 693
    DISPONE_EL_CUMPLIMIENTO_DE_LA_SENTENCIA = 540
    EN_RELACION_CON = 331
    ENMIENDAS = 247
    INTERPRETA = 402
    MODIFICA = 270
    MODIFICA_DETERMINADOS_PRECEPTOS = 272
    MODIFICA_EL_PLAN_PUBLICADO_POR = 271
    PRORROGA = 401
    PUBLICA = 300
    PUBLICA_ACUERDO_DE_CONVALIDACION = 301
    PUBLICA_EL_TEXTO_REVISADO = 303
    RATIFICA = 422
    RECURSO_PLANTEADO_EN_RELACION_CON = 694
    RECURSO_PROMOVIDO_CONTRA = 552
    SUPRIME = 235
    SUSPENDE = 231
    SUSTITUYE = 245
    TRANSPONE = 426
    TRANSPONE_PARCIALMENTE = 427

